<?php
/*
 * @copyright   Copyright (C) 2010-2023 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

use Combodo\iTop\Extension\SampleNewAttributeType\Form\Field\StringCustomField;

class AttributeStringCustomField extends AttributeString
{
	public static function GetFormFieldClass()
	{
		return StringCustomField::class;
	}

	public function GetEditClass()
	{
		return 'FormField';
	}

	/**
	 * @param $oHostObject
	 * @param $sFormPrefix
	 *
	 * @return string If returns null, then nothing is persisted.
	 *                Must return a value with the same type as the one returned by {@link static::MakeRealValue()}
	 */
	public function ReadValueFromPostedForm($oHostObject, $sFormPrefix)
	{
		$sPostedValue = utils::ReadPostedParam("attr_{$sFormPrefix}{$this->GetCode()}", '{}', 'raw_data');
		$aPostedValue = json_decode($sPostedValue, true);

		if (is_null($aPostedValue)) {
			return null;
		}

		$rawValue = $aPostedValue[$this->GetCode().'_field']; // '_field' suffix seems to be generated in iTop core when rendering form

		return $this->MakeRealValue($rawValue, $oHostObject);
	}

	public function MakeRealValue($proposedValue, $oHostObj)
	{
		// here we have a string att so nothing more to do
		return parent::MakeRealValue($proposedValue, $oHostObj); // TODO: Change the autogenerated stub
	}

	/**
	 * @param $sValue
	 * @param $oHostObject
	 * @param $bLocalize
	 *
	 * @return string HTML to be displayed in the details or lists
	 */
	public function GetAsHTML($sValue, $oHostObject = null, $bLocalize = true)
	{

		$sStringValue = parent::GetAsHTML($sValue, $oHostObject, $bLocalize);
		$sStringValue = '<i>Custom prefix</i> // '.$sStringValue.' // <i>Custom suffix</i>';

		return $sStringValue;
	}

	public function GetPrerequisiteAttributes($sClass = null)
	{
		// Overload here so that the field will be refreshed in the console
		return parent::GetPrerequisiteAttributes($sClass);
	}

}